### ISSUE TITLE
Allow for disabling of android keypad

### ISSUE THREAD

**Issue by Jeneral1** [yogeshpaliyal/Speld#2]
Hey man, I admire and appreciate your work. it is great. 

However, I realised that developers somethings create a Keypad view for a PINView in their design, I wanted to allow the user to be able to disable the android keypad which the user gets when the PINView is clicked.
![Screenshot 2022-05-19 091449](https://user-images.githubusercontent.com/25591282/169258676-a5895b3a-2858-4dc8-a776-53a251918cc1.jpg)

**Comment by yogeshpaliyal** [comment]
Thank you for your valuable feedback, will add a option to enable/disable custom keyboard

**Comment by Jeneral1** [comment]
Thanks, @yogeshpaliyal... it worked. 
I will let you know if any ideas come up again... Happy I could contribute too

**Comment by yogeshpaliyal** [comment]
Sure @Jeneral1 , You are always welcome with your ideas and contributes, thanks again 💚💚💚
